version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongo
      - rabbitmq
  redis:
    image: "redis:alpine"
  mongo:
    image: "mongo"
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"

